export const MAX_ADMINISTRATOR_CAPABILITY_HISTORY = 256;
export const MAX_ADMINISTRATOR_CAPABILITY_MS = 86_400_000;
export const MAX_CAPABILITY_SCOPE_BYTES = 12_000;
export const MAX_PARTY_CAPABILITY_HISTORY = 4_096;
